version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/skill-up:latest
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/skillup?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=skillup
      - SPRING_DATASOURCE_PASSWORD=skillup123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=skillup
      - MYSQL_USER=skillup
      - MYSQL_PASSWORD=skillup123
      - MYSQL_ROOT_PASSWORD=root123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: 